creator/characters/routes.py
from creator import db
from creator.models import Character
from creator.characters.utils import (get_armor_info, get_class_features, 
                                      get_char_traits, get_pact_boon, get_subclass_features, 
                                      get_weapon_info, roll_stats)
from creator.characters.forms import (AbilityScoreForm, AbilityScoreFormHuman, 
                                      EditCharacterForm, LevelUpForm, 
                                      NewCharacterForm, PactBoonForm, SubclassForm)
from creator.users.utils import gen_id
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user

characters = Blueprint('characters', __name__)


@characters.route('/new_character', methods=['GET', 'POST'])
def new_character():
    if current_user.is_authenticated:
        form = NewCharacterForm()
        stats = roll_stats()
        id = gen_id()
        if form.validate_on_submit():
            character = Character(id=id,
                                  name=form.name.data,
                                  ancestry=form.ancestry.data,
                                  heroic_class=form.heroic_class.data,
                                  weapon=form.weapon.data,
                                  armor=form.armor.data,
                                  player=current_user
                                  )
            db.session.add(character)
            db.session.commit()
            character.hp1 = character.roll_hp()
            db.session.commit()
            flash(f"{character.name} has been created!", 'success')
            return redirect(url_for('characters.ability_scores', character_id = id))
    else:
        flash('Please login', 'danger')
        return redirect(url_for('users.login'))
    return render_template('new_character.html', title='New Character',
                           form=form, stats=stats)

@characters.route('/<string:character_id>/ability_scores', methods=['GET', 'POST'])
def ability_scores(character_id):
    if current_user.is_authenticated:
        character = Character.query.get(character_id)
        if character.player != current_user:
            flash(f"{character.name} doesn't belong to you!")
            return redirect(url_for('characters.my_characters'))
        else:
            stats = roll_stats()
            if character.ancestry == 'Human':
                form = AbilityScoreFormHuman()
                human = True
                if form.validate_on_submit():
                    character.stat1 = stats[0]
                    character.stat2 = stats[1]
                    character.stat3 = stats[2]
                    character.stat4 = stats[3]
                    character.stat5 = stats[4]
                    character.stat6 = stats[5]
                    character.strength = form.strength.data + 1
                    character.dexterity = form.dexterity.data + 1
                    character.constitution = form.constitution.data + 1
                    character.intelligence = form.intelligence.data + 1
                    character.wisdom = form.wisdom.data + 1
                    character.charisma = form.charisma.data + 1
                    if character.heroic_class == 'Sorcerer' or character.heroic_class == 'Warlock':
                        db.session.commit()
                        flash(f'{character.name} gets to choose a subclass at level {character.level}.',
                            'success')
                        return redirect(url_for('characters.subclass_choice', character_id=character.id))
                    else:
                        db.session.commit()
                        flash(f'{character.name} has been created!', 'success')
                        return redirect(url_for('characters.character_sheet', character_id=character.id))
            else:
                form = AbilityScoreForm()
                plus_two = form.plustwo.data
                plus_one = form.plusone.data
                human = False
                if form.validate_on_submit():
                    character.stat1 = stats[0]
                    character.stat2 = stats[1]
                    character.stat3 = stats[2]
                    character.stat4 = stats[3]
                    character.stat5 = stats[4]
                    character.stat6 = stats[5]
                    character.strength = form.strength.data
                    character.dexterity = form.dexterity.data
                    character.constitution = form.constitution.data
                    character.intelligence = form.intelligence.data
                    character.wisdom = form.wisdom.data
                    character.charisma = form.charisma.data
                    exec('character.' + str(plus_two.lower()) + ' += 2')
                    exec('character.' + str(plus_one.lower()) + ' += 1')
                    db.session.commit()
                    if character.heroic_class == 'Sorcerer' or character.heroic_class == 'Warlock':
                        flash(f'{character.name} gets to choose a subclass at level {character.level}.',
                            'success')
                        return redirect(url_for('characters.subclass_choice', character_id=character.id))
                    else:
                        flash(f'{character.name} has been created!', 'success')
                        return redirect(url_for('characters.character_sheet', character_id=character.id))
    else:
        flash('Please login', 'danger')
        return redirect(url_for('users.login'))
    return render_template('ability_scores.html', 
                           title=f"{character.name}'s Ability Scores",
                           form=form, stats=stats, human=human)

@characters.route('/my_characters', methods=['GET', 'POST'])
def my_characters():
    if current_user.is_authenticated:
        return render_template('my_characters.html', title='My Characters')
    else:
        flash('Please login', 'danger')
        return redirect(url_for('users.login'))

@characters.route('/<string:character_id>/character_sheet', methods=['GET', 'POST'])
def character_sheet(character_id):
    if current_user.is_authenticated:
        character = Character.query.get(character_id)
        if character.subclass:
            subclass_dict = get_subclass_features(character.id)
        else:
            subclass_dict = None
        feat_dict = get_class_features(character.id)
        trait_dict = get_char_traits(character.id)
        weapon_dict = get_weapon_info(character.id)
        armor_dict = get_armor_info(character.id)
        if character.pact_boon:
            pact_boon = get_pact_boon(character.id)
        else:
            pact_boon = None
        char_hp = character.calc_hp()
        char_ac = character.calc_ac()
        prof_bonus = character.calc_prof()
        str_mod = character.calc_mod(character.strength)
        dex_mod = character.calc_mod(character.dexterity)
        con_mod = character.calc_mod(character.constitution)
        int_mod = character.calc_mod(character.intelligence)
        wis_mod = character.calc_mod(character.wisdom)
        cha_mod = character.calc_mod(character.charisma)
        return render_template('character_sheet.html', title='Character Sheet', 
                               character=character, feat_dict=feat_dict,
                               trait_dict=trait_dict, char_hp=char_hp,
                               str_mod=str_mod, dex_mod=dex_mod,
                               con_mod=con_mod, int_mod=int_mod,
                               wis_mod=wis_mod, cha_mod=cha_mod,
                               char_ac=char_ac, prof_bonus=prof_bonus,
                               armor_dict=armor_dict, weapon_dict=weapon_dict,
                               subclass_dict=subclass_dict, pact_boon=pact_boon)
    else:
        flash('Please login', 'danger')
        return redirect(url_for('users.login'))

@characters.route('/<string:character_id>/edit_character', methods=['GET', 'POST'])
def edit_character(character_id):
    if current_user.is_authenticated:
        character = Character.query.get(character_id)
        if character.player != current_user:
            flash(f"{character.name} doesn't belong to you!")
            return redirect(url_for('characters.my_characters'))
        else:
            form = EditCharacterForm()
            if form.validate_on_submit():
                character.name = form.name.data
                character.weapon = form.weapon.data
                character.armor = form.armor.data
                db.session.commit()
                flash(f'{character.name} has been updated!', 'success')
                return redirect(url_for('characters.character_sheet',
                                        character_id=character.id))
            elif request.method == 'GET':
                form.name.data = character.name
                form.weapon.data = character.weapon
                form.armor.data = character.armor
    else:
        flash('Please login', 'danger')
        return redirect(url_for('users.login'))
    return render_template('edit_character.html', title=f'Edit {character.name}',
                           form=form, character=character)

@characters.route('/<string:character_id>/level_up', methods=['GET', 'POST'])
def level_up(character_id):
    if current_user.is_authenticated:
        character = Character.query.get(character_id)
        if character.player != current_user:
            flash(f"{character.name} doesn't belong to you!")
            return redirect(url_for('characters.my_characters'))
        else:
            form = LevelUpForm()
            level = character.level
            if level == 20:
                flash(f'{character.name} is already max level!', 'danger')
                return redirect(url_for('characters.character_sheet',
                                character_id=character.id))
            level += 1

creator/main/routes.py
from flask import Blueprint, render_template
from flask import redirect, url_for
from flask_login import current_user

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    """
    Method to render the home page.
    """
    if current_user.is_authenticated:
        return redirect(url_for('characters.my_characters'))
    return render_template('home.html')

@main.route("/about")
def about():
    return render_template('about.html', title='About')

creator/users/routes.py
from creator import db, bcrypt
from creator.models import User
from creator.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm)
from creator.users.utils import gen_id
from flask import Blueprint, flash, redirect, request, render_template, url_for
from flask_login import current_user, login_user, login_required, logout_user

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        id = gen_id()
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(id=id, 
                    username=form.username.data, 
                    email=form.email.data, 
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)

creator/templates/character_sheet.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section char_box">
    <div class="media-body">
        <div class="article-metadata">
            <h2 class="charName">{{ character.name }}</h2>
            <h3>Level {{ character.level }} {{ character.ancestry }} 
                {% if character.subclass %}
                    {{ character.subclass }}
                {% endif %}
                {{ character.heroic_class }}</h3>
        </div>
    </div>
    <section class="NewExist sheet">
        <button type="button" class="btn btn-outline-danger btn-sm char_box">
            <a href="{{ url_for('characters.level_up', character_id=character.id) }}">Level Up</a>
        </button>
        <button type="button" class="btn btn-outline-danger btn-sm char_box">
            <a href="{{ url_for('characters.edit_character', character_id=character.id) }}">Edit</a>
        </button>
        <button type="button" class="btn btn-outline-danger btn-sm char_box">
            <a href="{{ url_for('characters.delete', character_id=character.id) }}">Delete</a>
        </button>
    </section>
</article>
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata ability_title">
            <h2>Ability Scores</h2>
            <div class="stat_container">
                <div class="row_col">
                    <div class="ability_scores">
                        <div class="per_stat">
                            <h3>STR</h3>
                            <h4>{{ character.strength }}</h4>
                            +{{ str_mod }}
                        </div>
                        <div class="per_stat">
                            <h3>DEX</h3>
                            <h4>{{ character.dexterity }}</h4>
                            +{{ dex_mod }}
                        </div>
                        <div class="per_stat">
                            <h3>CON</h3>
                            <h4>{{ character.constitution }}</h4>
                            +{{ con_mod }}
                        </div>
                        <div class="per_stat">
                            <h3>INT</h3>
                            <h4>{{ character.intelligence }}</h4>
                            +{{ int_mod }}
                        </div>
                        <div class="per_stat">
                            <h3>WIS</h3>
                            <h4>{{ character.wisdom }}</h4>
                            +{{ wis_mod }}
                        </div>
                        <div class="per_stat">    
                            <h3>CHA</h3>
                            <h4>{{ character.charisma }}</h4>
                            +{{ cha_mod }}
                        </div>
                    </div>
                </div>
                <div class="row_col">
                    <div class="ability_scores">
                        <div class="per_stat">
                            <h3>HP</h3> 
                            <h4>{{ char_hp }}</h4>
                        </div>
                        <div class="per_stat">
                            <h3>AC</h3>
                            <h4>{{ char_ac }}</h4>
                        </div>
                        <div class="per_stat">
                            <h3>Prof Bonus</h3>
                            <h4>+{{ prof_bonus }}</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata weapon">
            <h2>Weapon</h2>
            <div class="stat_container">
                <div class="ability_scores">
                    {% for key, value in weapon_dict.items() %}
                        <div class="per_stat">
                            <h4>{{ key }}:</h4>
                            {{ value }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</article>
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata armor">
            <h2>Armor</h2>
            <div class="stat_container">
                <div class="ability_scores">
                    {% for key, value in armor_dict.items() %}
                        <div class="per_stat">
                            <h4>{{ key }}:</h4>
                            {{ value }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</article>
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata ancestry">
            <h2>{{ character.ancestry }} Traits</h2>
            {% if trait_dict %}
            <div class="stat_container">
                {% for key, value in trait_dict.items() %}
                    <article class="media content-section" id="blocks">
                        <div class="media-body">
                            <div class="article-metadata">
                                <h4>{{ key }}</h4>
                                {% for item in value %}
                                <p style="color: black">{{ item }}</p>
                                {% endfor %}
                            </div>
                        </div>
                    </article>
                {% endfor %}
            {% elif character.ancestry == 'Human' %}
                <article class="media content-section">
                    <div class="media-body">
                        <div class="article-metadata">
                            <h4>Ability Score Increase</h4>
                            <p style="color: black">Your ability scores each increase by 1.</p>
                        </div>
                    </div>
                </article>
            <div class="stat_container">
            {% endif %}
        </div>
    </div>
</article>
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata class">
            <h2>{{ character.heroic_class }} Features</h2>
            <div class="stat_container">
            {% for key, value in feat_dict.items() %}
                <article class="media content-section" id="blocks">
                    <div class="media-body">
                        <div class="article-metadata">
                            <h4>{{ key }}</h4>
                            {% for item in value %}
                                <p style="color: black">{{ item }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </article>
            {% endfor %}
            </div>
        </div>
    </div>
</article>
{% if subclass_dict %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata class">
            <h2>{{ character.subclass }} Features</h2>
            <div class="stat_container"></div>
            {% for key, value in subclass_dict.items() %}
                <article class="media content-section" id="blocks">
                    <div class="media-body">
                        <div class="article-metadata">
                            <h4>{{ key }}</h4>
                            {% for item in value %}
                                <p style="color: black">{{ item }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </article>
            {% endfor %}
            </div>
        </div>
    </div>
</article>
{% endif %}
{% if pact_boon %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata class">
            <h2>Pact Boon</h2>
            <div class="stat_container"></div>
                <article class="media content-section" id="blocks">
                    <div class="media-body">
                        <div class="article-metadata">
                            <h4>{{ pact_boon.Name }}</h4>
                            {% for item in pact_boon.Description %}
                                <p style="color: black">{{ item }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
</article>
{% endif %}
{% endblock content %}

creator/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="background-image">
        <div class=welcome>
            <h1>
                Welcome to the HolB&D Character Creator!
            </h1>
            <section class="NewExist">
                <button type="button" class="btn btn-outline-dark btn-lg home">
                    <a href="{{ url_for('users.login') }}">Login</a>
                </button>
                <button type="button" class="btn btn-outline-dark btn-lg home">
                    <a href="{{ url_for('users.register') }}">Register</a>
                </button>
            </section>
        </div>
        {% if current_user.is_authenticated %}
            <p>
                Have fun creating your characters!
            </p>
    </div>
        <section class="NewExist">
            <button type="button" class="btn btn-outline-danger btn-lg">
                <a href="{{ url_for('characters.new_character') }}">Create New Character</a>
            </button>
            <button type="button" class="btn btn-outline-danger btn-lg">
                <a href="{{ url_for('characters.my_characters') }}">View My Characters</a>
            </button>
        </section>
        {% else %}
        {% endif %}
{% endblock content %}

creator/templates/layout.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">

        <!-- Mobile viewport meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CDN -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
        crossorigin="anonymous">

        <!-- Local CSS import -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='sheet.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='my_characters.css') }}">

        <!-- Code to change title depending on page -->
        {% if title %}
            <title>HolB&D - {{ title }}</title>
        {% else %}
            <title>HolB&D</title>
        {% endif %}

        <!-- Browser icon -->
        <link rel="icon" type="image/png" href="../static/images/dHolbie.png">
    </head>

    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="/">
                        <img src="../static/images/dHolbie.png">
                        HolB&D 5E Character Creator</a>
                    <button class="navbar-toggler" type="button" 
                    data-toggle="collapse" data-target="#navbarToggle" 
                    aria-controls="navbarToggle" aria-expanded="false"
                    aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <!-- Navbar Right Side -->
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            {% if current_user.is_authenticated %}
                                <a class="nav-item nav-link" href="{{ url_for('characters.my_characters') }}">Characters</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                            {% endif %}
                            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>

        <main role="main" class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Success & Error messages -->
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    <!-- Jinja inheritance block -->
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </main>

        <footer class="site-footer">
            <div class="footer bg-steel fixed-bottom text-center">
                Project for Holberton School Tulsa - Uses content from the
                Dungeons & Dragons 5th Edition SRD
            </div>
        </footer>

        <!-- Bootstrap CDN -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" 
        crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" 
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" 
        crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
        crossorigin="anonymous"></script>

    </body>

</html>

creator/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">	
                {{ form.submit(class="btn btn-outline-info") }}	
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

creator/templates/my_characters.html
{% extends "layout.html" %}
{% block content %}
<h1 class="mb-3 username">Characters: {{ current_user.characters.total }}</h1>
</article>  
<div class="my_chars_cnc">
    <button type="button" class="btn btn-outline-danger btn-lg cnc">
        <a class="mr-2" style="color: black" href="{{ url_for('characters.new_character') }}">Create a New Character</a>
    </button>  
</div>
    {% for character in current_user.characters %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <h2><a style="color: #bd1f0a" class="mr-2" href="{{ url_for('characters.character_sheet', character_id=character.id) }}">
                        {{ character.name }}
                    </a></h2>
                    <h2><a class="article-title">Level {{ character.level }} {{ character.ancestry }} {{ character.heroic_class }}</a></h2>
                    <small class="text-muted">Created on: {{ character.date_created.strftime('%Y-%m-%d') }}</small>
                </div>
            </div>
            <section class="NewExist my_chars">
                <button type="button" class="btn btn-outline-danger btn-lg my_chars">
                    <a href="{{ url_for('characters.level_up', character_id=character.id) }}">Level Up</a>
                </button>
                <button type="button" class="btn btn-outline-danger btn-lg my_chars" >
                    <a href="{{ url_for('characters.edit_character', character_id=character.id) }}">Edit</a>
                </button>
                <button type="button" class="btn btn-outline-danger btn-lg my_chars">
                    <a href="{{ url_for('characters.delete', character_id=character.id) }}">Delete</a>
                </button>
            </section>
        </article>
    {% endfor %}
{% endblock content %}